version: '3'
services:
  authorizer:
    container_name: authorizer
    image: lakhansamani/authorizer:local
    environment:
      - DATABASE_URL=data.db
      - DATABASE_TYPE=sqlite
    ports:
      - '8080:8080'
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - authorizer
    ports:
      - 80:80
